# Matrix in Numpy Array.

In [7]:
import numpy as np 
var=np.matrix([[1,2,3],[1,2,3]])
v=np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))
print()
print(var+v)

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[2 4 6]
 [2 4 6]]


# Matrix Multiplication in Numpy array.

In [14]:
var=np.matrix([[1,2],[1,2]])
v=np.matrix([[1,2,],[1,2]])
print(var)
print(type(var))
print()
print(var*v)
print()
print(var.dot(v))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>

[[3 6]
 [3 6]]

[[3 6]
 [3 6]]


# Array in Numpy.

In [8]:
var1=np.array([[1,2,3],[1,2,3]])
var2=np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))
print()
print(var1+var2)


[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>

[[2 4 6]
 [2 4 6]]


# Array Multiplication

In [16]:
var1=np.array([[1,2],[1,2]])
var2=np.array([[1,2],[1,2]])
print(var1)
print(type(var1))
print()
print(var1*var2)


[[1 2]
 [1 2]]
<class 'numpy.ndarray'>

[[1 4]
 [1 4]]
