# Iterating Numpy Arrays.

In [1]:
import numpy as np
var=np.array([100,101,102,103,104,105])
for i in var:
    print(i)


100
101
102
103
104
105


# 2-Dimesion Arrays.

In [4]:
var1=np.array([[11,12,13,14,15],[21,22,23,24,25]])
print(var1)
print()
for i in var1:
    for j in i:
        print(j)

[[11 12 13 14 15]
 [21 22 23 24 25]]

11
12
13
14
15
21
22
23
24
25


# 3-Dimension Arrays.

In [7]:
var2=np.array([[[31,32,33,34,35],[36,37,38,39,40],[41,42,43,44,45]]])
print(var2)
print()
for i in var2:
    for j in i:
        for k in j:
            print(k)

[[[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]]

31
32
33
34
35
36
37
38
39
40
41
42
43
44
45


In [13]:
var2=np.array([[[31,32,33,34,35],[36,37,38,39,40],[41,42,43,44,45]]])
print(var2)
print()
for i in np.nditer(var2):
    print(i)

[[[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]]

31
32
33
34
35
36
37
38
39
40
41
42
43
44
45


In [19]:
var3=np.array([[[31,32,33,34,35],[36,37,38,39,40],[41,42,43,44,45]]])
print(var3)
print()
for i,d in np.ndenumerate(var3):
    print(i,d)

[[[31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]]]

(0, 0, 0) 31
(0, 0, 1) 32
(0, 0, 2) 33
(0, 0, 3) 34
(0, 0, 4) 35
(0, 1, 0) 36
(0, 1, 1) 37
(0, 1, 2) 38
(0, 1, 3) 39
(0, 1, 4) 40
(0, 2, 0) 41
(0, 2, 1) 42
(0, 2, 2) 43
(0, 2, 3) 44
(0, 2, 4) 45
