# 1)Insert()

In [4]:
import numpy as np 
var=np.array([1,2,3,4,5])
print(var)
print()
NEW=np.insert(var,2,40)
print(NEW)

[1 2 3 4 5]

[ 1  2 40  3  4  5]


In [6]:
var=np.array([1,2,3,4,5])
print(var)
print()
NEW=np.insert(var,(2,4),40)
print(NEW)

[1 2 3 4 5]

[ 1  2 40  3  4 40  5]


In [7]:
var=np.array([[1,2,3],[4,5,6]])
print(var)
print()
NEW=np.insert(var,2,40,axis=0)
print(NEW)

[[1 2 3]
 [4 5 6]]

[[ 1  2  3]
 [ 4  5  6]
 [40 40 40]]


# 2)append()

In [5]:
var=np.array([1,2,3,4,5])
print(var)
print()
NEW=np.append(var,40)
print(NEW)

[1 2 3 4 5]

[ 1  2  3  4  5 40]


# 3)Delete()

In [8]:
var=np.array([1,2,3,4,5])
print(var)
print()
NEW=np.delete(var,2)
print(NEW)

[1 2 3 4 5]

[1 2 4 5]
