# Join Two Numpy Arrays.


In [4]:
import numpy as np 
var=np.array([1,2,3,4,5])
var1=np.array([6,7,8,9,10])
join=np.concatenate((var,var1))
print(join)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
import numpy as np 
var=np.array([[1,2,3,4,5],[6,7,8,9,10]])
var1=np.array([[11,12,13,14,15],[16,17,18,19,20]])
join=np.concatenate((var,var1),axis=1)
print(join)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


# stack() Function

In [17]:
var_1=np.array([1,2,3,4,5])
var_2=np.array([6,7,8,9,10])
new_ar=np.stack((var_1,var_2),axis=0)
print(new_ar)
print()
new_ar1=np.hstack((var_1,var_2))       #row
print(new_ar1)
print()
new_ar2=np.vstack((var_1,var_2))       #column
print(new_ar2)
print()
new_ar3=np.dstack((var_1,var_2))       #height
print(new_ar3)
print()



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 1  2  3  4  5  6  7  8  9 10]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]

