# Random

# 1)rand()                          (0-1)

In [1]:
import numpy as np
var1=np.random.rand(5)
print(var1)

[0.06281862 0.07441649 0.56370115 0.01207031 0.58903697]


In [3]:
var_1=np.random.rand(5,4)
print(var_1)

[[0.93354276 0.34405582 0.99557899 0.74691475]
 [0.10927885 0.16455876 0.88466124 0.4675894 ]
 [0.44114267 0.12679155 0.84545637 0.31206633]
 [0.69086624 0.83361555 0.14835005 0.41800725]
 [0.40190291 0.72518663 0.11523511 0.61104063]]


# 2)randn()   

In [4]:
var2=np.random.randn(5)
print(var2)

[-0.69852545  0.46082274 -0.52477436 -0.29414905  0.02376864]


# 3)ranf()

In [6]:
var3=np.random.ranf(5)
print(var3)

[0.38768582 0.67759277 0.50768734 0.01906543 0.6905721 ]


# 4)randint()

In [14]:
var4=np.random.randint(5,20,5)
print(var4)

[16 18 17 14  5]
