# Numpy Array Functions_2.

1)shuffle()

2)unique()

3)resize()

4)flatten()

5)ravel()

# 1)shuffle()

In [5]:
import numpy as np
var4=np.array([1,2,3,4,5,6,7,8,9])
np.random.shuffle(var4)
print(var4)

[7 5 2 8 4 6 3 1 9]


# 2)unique()

In [7]:
var2=np.array([1,2,2,2,3,4,5,5,6,4,6,4,6,4,6,4,5])
v=np.unique(var2)
print(v)


[1 2 3 4 5 6]


# 3)resize()

In [11]:
var3=np.array([1,2,3,4,5,6])
v=np.resize(var3,(2,3))
print(v)

[[1 2 3]
 [4 5 6]]


In [12]:
var3=np.array([1,2,3,4,5,6])
v=np.resize(var3,(3,2))
print(v)

[[1 2]
 [3 4]
 [5 6]]


# 4)flatten()

In [18]:
var4=np.array([[1,2,3,4,5],[6,7,8,9,10]])
v=(var4.flatten())
print(v)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
var4=np.array([[1,2,3,4,5],[6,7,8,9,10]])
v=(var4.flatten(order="C"))
print(v)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
var4=np.array([[1,2,3,4,5],[6,7,8,9,10]])
v=(var4.flatten(order="F"))
print(v)

[ 1  6  2  7  3  8  4  9  5 10]


In [21]:
var4=np.array([[1,2,3,4,5],[6,7,8,9,10]])
v=(var4.flatten(order="A"))
print(v)

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
var4=np.array([[1,2,3,4,5],[6,7,8,9,10]])
v=(var4.flatten(order="K"))
print(v)

[ 1  2  3  4  5  6  7  8  9 10]


# 5)ravel()

In [27]:
var4=np.array([[1,2,3,4,5],[6,7,8,9,10]])
v=np.ravel(var4)
print(v)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
var4=np.array([[1,2,3,4,5],[6,7,8,9,10]])
v=np.ravel(var4,order="F")
print(v)