# 1)Zeroes


In [1]:
import numpy as np
ar_zero=np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [4]:
ar_zero1=np.zeros((4,3))
print(ar_zero1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 2)ones

In [2]:
ar_ones=np.ones(4)
print(ar_ones)

[1. 1. 1. 1.]


In [6]:
ar_ones1=np.ones((4,3))
print(ar_ones1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# 3)empty

In [7]:
ar_em=np.empty(4)
print(ar_em)            #Previous Memory

[1. 1. 1. 1.]


# 4)Diagonal

In [8]:
ar_dia=np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 5)linspace

In [10]:
ar_lin=np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
